[package]
name = "metrics_one_models"
version = "0.1.0"
edition = "2024"

[dependencies]
metrics_one_macros = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true }
