receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  postgresql:
    endpoint: database:5432
    transport: tcp
    username: api
    password: MetricsOne
    databases: ["metrics-one"]
    tls:
      insecure: true # TODO: change to false when TLS is enabled

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"
  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true # TODO: change to false when TLS is enabled
  debug:
    verbosity: normal

service:
  pipelines:
    metrics:
      receivers: [otlp, postgresql]
      exporters: [prometheus, debug]
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, debug]
